export const seoKeywords = [
  // 主要节日倒计时关键词
  "holiday countdown", "next holiday", "holiday timer", "christmas countdown", "new year countdown", 
  "thanksgiving countdown", "global holidays", "holiday tracker", "halloween countdown", "easter countdown",
  "valentine countdown", "diwali countdown", "chinese new year countdown", "ramadan countdown", "hanukkah countdown",
  "kwanzaa countdown", "independence day countdown", "labor day countdown", "memorial day countdown",
  "veterans day countdown", "presidents day countdown", "martin luther king day countdown", "columbus day countdown",
  "groundhog day countdown", "st patricks day countdown", "mothers day countdown", "fathers day countdown",
  "grandparents day countdown", "childrens day countdown", "teachers day countdown", "nurses day countdown",
  "doctors day countdown", "world health day countdown", "earth day countdown", "world environment day countdown",
  "international womens day countdown", "international mens day countdown", "world peace day countdown",
  "world food day countdown", "world water day countdown", "world book day countdown", "world music day countdown",
  "world dance day countdown", "world theatre day countdown", "world cinema day countdown", "world photography day countdown",
  "world art day countdown", "world poetry day countdown", "world literature day countdown", "world science day countdown",
  "world mathematics day countdown", "world engineering day countdown", "world architecture day countdown",
  "world design day countdown", "world creativity day countdown", "world innovation day countdown",
  "world technology day countdown", "world internet day countdown", "world social media day countdown",
  "world communication day countdown", "world press day countdown", "world radio day countdown",
  "world television day countdown", "world film day countdown", "world animation day countdown",
  "world gaming day countdown", "world esports day countdown", "world sports day countdown",
  "world olympics day countdown", "world football day countdown", "world basketball day countdown",
  "world tennis day countdown", "world golf day countdown", "world swimming day countdown",
  "world running day countdown", "world cycling day countdown", "world hiking day countdown",
  "world camping day countdown", "world fishing day countdown", "world hunting day countdown",
  "world gardening day countdown", "world farming day countdown", "world cooking day countdown",
  "world baking day countdown", "world coffee day countdown", "world tea day countdown",
  "world wine day countdown", "world beer day countdown", "world chocolate day countdown",
  "world pizza day countdown", "world hamburger day countdown", "world sushi day countdown",
  "world pasta day countdown", "world rice day countdown", "world bread day countdown",
  "world milk day countdown", "world egg day countdown", "world meat day countdown",
  "world vegetarian day countdown", "world vegan day countdown", "world organic day countdown",
  "world fair trade day countdown", "world recycling day countdown", "world conservation day countdown",
  "world wildlife day countdown", "world animal day countdown", "world pet day countdown",
  "world dog day countdown", "world cat day countdown", "world bird day countdown",
  "world fish day countdown", "world insect day countdown", "world plant day countdown",
  "world tree day countdown", "world flower day countdown", "world seed day countdown",
  "world soil day countdown", "world water day countdown", "world air day countdown",
  "world climate day countdown", "world weather day countdown", "world storm day countdown",
  "world hurricane day countdown", "world tornado day countdown", "world earthquake day countdown",
  "world volcano day countdown", "world tsunami day countdown", "world flood day countdown",
  "world drought day countdown", "world fire day countdown", "world ice day countdown",
  "world snow day countdown", "world rain day countdown", "world sunshine day countdown",
  "world cloud day countdown", "world rainbow day countdown", "world lightning day countdown",
  "world thunder day countdown", "world fog day countdown", "world mist day countdown",
  "world dew day countdown", "world frost day countdown", "world hail day countdown",
  "world sleet day countdown", "world blizzard day countdown", "world avalanche day countdown",
  "world landslide day countdown", "world mudslide day countdown", "world rockslide day countdown",
  "world sinkhole day countdown", "world cave day countdown", "world mountain day countdown",
  "world hill day countdown", "world valley day countdown", "world canyon day countdown",
  "world gorge day countdown", "world ravine day countdown", "world cliff day countdown",
  "world bluff day countdown", "world ridge day countdown", "world peak day countdown",
  "world summit day countdown", "world crest day countdown", "world top day countdown",
  "world height day countdown", "world elevation day countdown", "world altitude day countdown",
  "world depth day countdown", "world bottom day countdown", "world base day countdown",
  "world foundation day countdown", "world ground day countdown", "world floor day countdown",
  "world surface day countdown", "world level day countdown", "world plane day countdown",
  "world flat day countdown", "world smooth day countdown", "world rough day countdown",
  "world bumpy day countdown", "world uneven day countdown", "world irregular day countdown",
  "world regular day countdown", "world normal day countdown", "world standard day countdown",
  "world typical day countdown", "world usual day countdown", "world common day countdown",
  "world ordinary day countdown", "world average day countdown", "world median day countdown",
  "world middle day countdown", "world center day countdown", "world central day countdown",
  "world core day countdown", "world heart day countdown", "world soul day countdown",
  "world spirit day countdown", "world mind day countdown", "world brain day countdown",
  "world head day countdown", "world face day countdown", "world eye day countdown",
  "world ear day countdown", "world nose day countdown", "world mouth day countdown",
  "world tongue day countdown", "world tooth day countdown", "world lip day countdown",
  "world cheek day countdown", "world chin day countdown", "world jaw day countdown",
  "world neck day countdown", "world throat day countdown", "world shoulder day countdown",
  "world arm day countdown", "world elbow day countdown", "world wrist day countdown",
  "world hand day countdown", "world finger day countdown", "world thumb day countdown",
  "world palm day countdown", "world back day countdown", "world chest day countdown",
  "world stomach day countdown", "world belly day countdown", "world waist day countdown",
  "world hip day countdown", "world leg day countdown", "world knee day countdown",
  "world ankle day countdown", "world foot day countdown", "world toe day countdown",
  "world heel day countdown", "world sole day countdown", "world arch day countdown",
  "world ball day countdown", "world joint day countdown", "world bone day countdown",
  "world muscle day countdown", "world tendon day countdown", "world ligament day countdown",
  "world nerve day countdown", "world vein day countdown", "world artery day countdown",
  "world blood day countdown", "world heart day countdown", "world lung day countdown",
  "world liver day countdown", "world kidney day countdown", "world stomach day countdown",
  "world intestine day countdown", "world colon day countdown", "world bladder day countdown",
  "world uterus day countdown", "world ovary day countdown", "world testicle day countdown",
  "world prostate day countdown", "world breast day countdown", "world nipple day countdown",
  "world skin day countdown", "world hair day countdown", "world nail day countdown",
  "world sweat day countdown", "world tear day countdown", "world saliva day countdown",
  "world mucus day countdown", "world phlegm day countdown", "world bile day countdown",
  "world urine day countdown", "world feces day countdown", "world gas day countdown",
  "world wind day countdown", "world breath day countdown", "world air day countdown",
  "world oxygen day countdown", "world carbon day countdown", "world nitrogen day countdown",
  "world hydrogen day countdown", "world helium day countdown", "world neon day countdown",
  "world argon day countdown", "world krypton day countdown", "world xenon day countdown",
  "world radon day countdown", "world uranium day countdown", "world plutonium day countdown",
  "world thorium day countdown", "world radium day countdown", "world polonium day countdown",
  "world actinium day countdown", "world protactinium day countdown", "world neptunium day countdown",
  "world americium day countdown", "world curium day countdown", "world berkelium day countdown",
  "world californium day countdown", "world einsteinium day countdown", "world fermium day countdown",
  "world mendelevium day countdown", "world nobelium day countdown", "world lawrencium day countdown",
  "world rutherfordium day countdown", "world dubnium day countdown", "world seaborgium day countdown",
  "world bohrium day countdown", "world hassium day countdown", "world meitnerium day countdown",
  "world darmstadtium day countdown", "world roentgenium day countdown", "world copernicium day countdown",
  "world nihonium day countdown", "world flerovium day countdown", "world moscovium day countdown",
  "world livermorium day countdown", "world tennessine day countdown", "world oganesson day countdown",
  
  // 工具相关关键词
  "financial calculator", "mortgage calculator", "investment calculator", "budget planner",
  "time management tools", "schedule planner", "countdown timer", "task manager",
  "unit converter", "length converter", "weight converter", "currency converter",
  "health calculator", "bmi calculator", "calorie calculator", "fitness tracker",
  
  // 通用关键词
  "free online tools", "web calculator", "online timer", "digital countdown",
  "holiday planner", "event countdown", "celebration tracker", "festival countdown",
  "global celebrations", "world festivals", "cultural holidays", "religious holidays",
  "national holidays", "international holidays", "seasonal celebrations", "annual events",
  "countdown app", "timer app", "holiday app", "calendar app", "reminder app",
  "notification app", "alarm app", "stopwatch app", "chronometer app", "timekeeper app"
].join(", "); 